package tec.views;

public class FingerprintRec extends javax.swing.JPanel {    
    public FingerprintRec() {
        initComponents();
    }
    
//     public void setView (String option){
//        PreLoader view = new PreLoader();
//      
//        view.setLocation(0, 0);
//        view.setSize(contentFingerRec.getWidth(), contentFingerRec.getHeight());
//
//        contentFingerRec.removeAll();
//        contentFingerRec.add(view, BorderLayout.CENTER);
//        contentFingerRec.revalidate();
//        contentFingerRec.repaint();
//            
//        optionView = option;
//        timerPreloader.start();  
//    }
//     
//     Timer timerPreloader = new Timer(2000, new ActionListener() {
//        public void actionPerformed(ActionEvent e) {
//            JPanel view = new JPanel();
//            if(optionView.equals("homeFingerRec")){
//                view = new HomeFingerRec();
//            } else if(optionView.equals("newFingerprint")){
//                view = new NewFingerprint(model);
//            }
//
//            view.setLocation(0, 0);
//            view.setSize(contentFingerRec.getWidth(), contentFingerRec.getHeight());
//
//            contentFingerRec.removeAll();
//            contentFingerRec.add(view, BorderLayout.CENTER);
//            contentFingerRec.revalidate();
//            contentFingerRec.repaint();
//            timerPreloader.stop();
//        }
//    });
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        imgTouchTrack = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        noControlLabel = new javax.swing.JLabel();
        noControlTextField = new javax.swing.JTextField();
        noControlLine = new javax.swing.JPanel();
        btnSearch = new javax.swing.JPanel();
        btnSearchLabel = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        imgStudent = new javax.swing.JLabel();
        fullnameLabel = new javax.swing.JLabel();
        fullnameTextField = new javax.swing.JTextField();
        fullnameLine = new javax.swing.JPanel();
        careerLabel = new javax.swing.JLabel();
        careerTextField = new javax.swing.JTextField();
        careerLine = new javax.swing.JPanel();
        alertPanel = new javax.swing.JPanel();
        alertTitle = new javax.swing.JLabel();
        alertBody = new javax.swing.JLabel();
        actionsPanel = new javax.swing.JPanel();
        btnNewFinger = new javax.swing.JPanel();
        btnNewFingerLabel = new javax.swing.JLabel();
        btnVerify = new javax.swing.JPanel();
        btnVerifyLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        semesterLabel = new javax.swing.JLabel();
        semesterTextField = new javax.swing.JTextField();
        semesterLine = new javax.swing.JPanel();
        groupLabel = new javax.swing.JLabel();
        groupTextField = new javax.swing.JTextField();
        groupLine = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1200, 700));

        imgTouchTrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/touchtrack80px.png"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 18)); // NOI18N
        titleLabel.setText("Registo de huella");

        noControlLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        noControlLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noControlLabel.setText("Numero de control");
        noControlLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        noControlTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        noControlTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        noControlTextField.setBorder(null);
        noControlTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noControlTextFieldKeyTyped(evt);
            }
        });

        noControlLine.setBackground(new java.awt.Color(102, 102, 102));
        noControlLine.setToolTipText("");
        noControlLine.setPreferredSize(new java.awt.Dimension(250, 2));

        javax.swing.GroupLayout noControlLineLayout = new javax.swing.GroupLayout(noControlLine);
        noControlLine.setLayout(noControlLineLayout);
        noControlLineLayout.setHorizontalGroup(
            noControlLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        noControlLineLayout.setVerticalGroup(
            noControlLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        btnSearch.setBackground(new java.awt.Color(51, 23, 156));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchLabel.setText("Buscar");
        btnSearchLabel.setToolTipText("");
        btnSearchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchLabelMouseExited(evt);
            }
        });
        btnSearch.add(btnSearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        studentPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));

        imgStudent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        fullnameLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        fullnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fullnameLabel.setText("Nombre completo");
        fullnameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        fullnameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fullnameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fullnameTextField.setBorder(null);
        fullnameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fullnameTextField.setEnabled(false);
        fullnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullnameTextFieldKeyTyped(evt);
            }
        });

        fullnameLine.setBackground(new java.awt.Color(102, 102, 102));
        fullnameLine.setToolTipText("");
        fullnameLine.setPreferredSize(new java.awt.Dimension(300, 2));

        javax.swing.GroupLayout fullnameLineLayout = new javax.swing.GroupLayout(fullnameLine);
        fullnameLine.setLayout(fullnameLineLayout);
        fullnameLineLayout.setHorizontalGroup(
            fullnameLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        fullnameLineLayout.setVerticalGroup(
            fullnameLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        careerLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        careerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        careerLabel.setText("Carrera");
        careerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        careerTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        careerTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        careerTextField.setBorder(null);
        careerTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        careerTextField.setEnabled(false);
        careerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                careerTextFieldKeyTyped(evt);
            }
        });

        careerLine.setBackground(new java.awt.Color(102, 102, 102));
        careerLine.setToolTipText("");
        careerLine.setPreferredSize(new java.awt.Dimension(300, 2));

        javax.swing.GroupLayout careerLineLayout = new javax.swing.GroupLayout(careerLine);
        careerLine.setLayout(careerLineLayout);
        careerLineLayout.setHorizontalGroup(
            careerLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        careerLineLayout.setVerticalGroup(
            careerLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        alertPanel.setVisible(false);
        alertPanel.setBackground(new java.awt.Color(255, 77, 99));
        alertPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alertTitle.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 14)); // NOI18N
        alertTitle.setForeground(new java.awt.Color(255, 255, 255));
        alertTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alertTitle.setText("¡Ocurrio un error!");
        alertTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        alertPanel.add(alertTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 30));

        alertBody.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 12)); // NOI18N
        alertBody.setForeground(new java.awt.Color(255, 255, 255));
        alertBody.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alertBody.setText("¡Ocurrio un error!");
        alertBody.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        alertPanel.add(alertBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 40));

        actionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        actionsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));

        btnNewFinger.setBackground(new java.awt.Color(51, 23, 156));
        btnNewFinger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewFingerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewFingerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewFingerMouseExited(evt);
            }
        });
        btnNewFinger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewFingerLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnNewFingerLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnNewFingerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNewFingerLabel.setText("Nueva huella");
        btnNewFingerLabel.setToolTipText("");
        btnNewFingerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewFingerLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewFingerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewFingerLabelMouseExited(evt);
            }
        });
        btnNewFinger.add(btnNewFingerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        btnVerify.setBackground(new java.awt.Color(51, 23, 156));
        btnVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerifyMouseExited(evt);
            }
        });
        btnVerify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerifyLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnVerifyLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerifyLabel.setText("Verificar huella");
        btnVerifyLabel.setToolTipText("");
        btnVerifyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerifyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerifyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerifyLabelMouseExited(evt);
            }
        });
        btnVerify.add(btnVerifyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        javax.swing.GroupLayout actionsPanelLayout = new javax.swing.GroupLayout(actionsPanel);
        actionsPanel.setLayout(actionsPanelLayout);
        actionsPanelLayout.setHorizontalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnNewFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        actionsPanelLayout.setVerticalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        semesterLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        semesterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        semesterLabel.setText("Semestre");
        semesterLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        semesterTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        semesterTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        semesterTextField.setBorder(null);
        semesterTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        semesterTextField.setEnabled(false);
        semesterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semesterTextFieldKeyTyped(evt);
            }
        });

        semesterLine.setBackground(new java.awt.Color(102, 102, 102));
        semesterLine.setToolTipText("");
        semesterLine.setPreferredSize(new java.awt.Dimension(300, 2));

        javax.swing.GroupLayout semesterLineLayout = new javax.swing.GroupLayout(semesterLine);
        semesterLine.setLayout(semesterLineLayout);
        semesterLineLayout.setHorizontalGroup(
            semesterLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        semesterLineLayout.setVerticalGroup(
            semesterLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        groupLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        groupLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        groupLabel.setText("Grupo");
        groupLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        groupTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        groupTextField.setBorder(null);
        groupTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        groupTextField.setEnabled(false);
        groupTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                groupTextFieldKeyTyped(evt);
            }
        });

        groupLine.setBackground(new java.awt.Color(102, 102, 102));
        groupLine.setToolTipText("");
        groupLine.setPreferredSize(new java.awt.Dimension(300, 2));

        javax.swing.GroupLayout groupLineLayout = new javax.swing.GroupLayout(groupLine);
        groupLine.setLayout(groupLineLayout);
        groupLineLayout.setHorizontalGroup(
            groupLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        groupLineLayout.setVerticalGroup(
            groupLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("<html><p>Desarrollado por los alumnos del plantel Tecnológico Arandas de Ingeniería en sistemas computacionales de séptimo semestre. © 2023 Tecnológico Arandas.</p></html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(imgTouchTrack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(careerLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(careerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(careerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fullnameLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fullnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fullnameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(noControlTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(noControlLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noControlLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(semesterLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(semesterTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(semesterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(groupLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(groupTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(groupLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1332, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imgTouchTrack))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(titleLabel))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(alertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fullnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(fullnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(fullnameLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(careerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(careerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(careerLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(noControlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(noControlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(noControlLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(semesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(semesterLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(groupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(groupLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(actionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewFingerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerMouseExited
//        btnNewFinger.setBackground(colorPrimary);
    }//GEN-LAST:event_btnNewFingerMouseExited

    private void btnNewFingerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerMouseEntered
//        btnNewFinger.setBackground(colorSecondary);
    }//GEN-LAST:event_btnNewFingerMouseEntered

    private void btnNewFingerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerMouseClicked
//        if(model.get_student_id() == null){
//            alertPanel(colorDanger, "!Ocurrio un error!", "Selecciona algun alumno!");
//        } else {
//            btnNewFinger.setBackground(colorPrimary);
//            setView("newFingerprint");
//        }
        
    }//GEN-LAST:event_btnNewFingerMouseClicked

    private void btnNewFingerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerLabelMouseExited
//        btnNewFinger.setBackground(colorPrimary);
    }//GEN-LAST:event_btnNewFingerLabelMouseExited

    private void btnNewFingerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerLabelMouseEntered
//        btnNewFinger.setBackground(colorSecondary);
    }//GEN-LAST:event_btnNewFingerLabelMouseEntered

    private void btnNewFingerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFingerLabelMouseClicked
//        if(model.get_student_id() == null){
//            alertPanel(colorDanger, "!Ocurrio un error!", "Selecciona algun alumno!");
//        } else {
//            btnNewFinger.setBackground(colorPrimary);
//            setView("newFingerprint");
//        }
    }//GEN-LAST:event_btnNewFingerLabelMouseClicked

    private void careerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_careerTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_careerTextFieldKeyTyped

    private void fullnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnameTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameTextFieldKeyTyped

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchLabelMouseExited
    }//GEN-LAST:event_btnSearchLabelMouseExited

    private void btnSearchLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchLabelMouseEntered
    }//GEN-LAST:event_btnSearchLabelMouseEntered

    private void btnSearchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchLabelMouseClicked
    }//GEN-LAST:event_btnSearchLabelMouseClicked

    private void noControlTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noControlTextFieldKeyTyped
    }//GEN-LAST:event_noControlTextFieldKeyTyped

    private void btnVerifyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyLabelMouseClicked

    private void btnVerifyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyLabelMouseEntered

    private void btnVerifyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyLabelMouseExited

    private void btnVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyMouseClicked

    private void btnVerifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyMouseEntered

    private void btnVerifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyMouseExited

    private void semesterTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesterTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterTextFieldKeyTyped

    private void groupTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_groupTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    public javax.swing.JLabel alertBody;
    public javax.swing.JPanel alertPanel;
    public javax.swing.JLabel alertTitle;
    private javax.swing.JPanel bodyPanel;
    public javax.swing.JPanel btnNewFinger;
    public javax.swing.JLabel btnNewFingerLabel;
    public javax.swing.JPanel btnSearch;
    public javax.swing.JLabel btnSearchLabel;
    public javax.swing.JPanel btnVerify;
    public javax.swing.JLabel btnVerifyLabel;
    public javax.swing.JLabel careerLabel;
    public javax.swing.JPanel careerLine;
    public javax.swing.JTextField careerTextField;
    public javax.swing.JPanel contentPanel;
    public javax.swing.JLabel fullnameLabel;
    public javax.swing.JPanel fullnameLine;
    public javax.swing.JTextField fullnameTextField;
    public javax.swing.JLabel groupLabel;
    public javax.swing.JPanel groupLine;
    public javax.swing.JTextField groupTextField;
    public javax.swing.JLabel imgStudent;
    private javax.swing.JLabel imgTouchTrack;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel noControlLabel;
    public javax.swing.JPanel noControlLine;
    public javax.swing.JTextField noControlTextField;
    public javax.swing.JLabel semesterLabel;
    public javax.swing.JPanel semesterLine;
    public javax.swing.JTextField semesterTextField;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
