package tec.views;

import java.awt.Color;

public class Login extends javax.swing.JFrame {
                
    public Login() {        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        decorativePanel = new javax.swing.JPanel();
        imgTec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        alertPanel = new javax.swing.JPanel();
        alertTitle = new javax.swing.JLabel();
        alertBody = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        touchtrackLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        userLine = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        passwordLine = new javax.swing.JPanel();
        btnLogin = new javax.swing.JPanel();
        btnLoginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decorativePanel.setBackground(new java.awt.Color(51, 23, 156));
        decorativePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                decorativePanelMouseDragged(evt);
            }
        });
        decorativePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decorativePanelMousePressed(evt);
            }
        });
        decorativePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/tec-efecto.png"))); // NOI18N
        decorativePanel.add(imgTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/back.png"))); // NOI18N
        decorativePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));
        jLabel1.getAccessibleContext().setAccessibleName("");

        mainPanel.add(decorativePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        alertPanel.setVisible(false);
        alertPanel.setBackground(new java.awt.Color(255, 77, 99));
        alertPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alertTitle.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 14)); // NOI18N
        alertTitle.setForeground(new java.awt.Color(255, 255, 255));
        alertTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alertTitle.setText("¡Ocurrio un error!");
        alertTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        alertPanel.add(alertTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 30));

        alertBody.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 12)); // NOI18N
        alertBody.setForeground(new java.awt.Color(255, 255, 255));
        alertBody.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        alertBody.setText("¡Ocurrio un error!");
        alertBody.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        alertPanel.add(alertBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 60));

        mainPanel.add(alertPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 300, 110));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/iconClose.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        mainPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/touchtrack80px.png"))); // NOI18N
        mainPanel.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        touchtrackLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 14)); // NOI18N
        touchtrackLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        touchtrackLabel.setText("TouchTrack");
        touchtrackLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainPanel.add(touchtrackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 90, 40));

        versionLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 14)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(102, 102, 102));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        versionLabel.setText("V.2.0.0");
        versionLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainPanel.add(versionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 90, 30));

        loginLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 1, 24)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLabel.setText("Iniciar sesion");
        loginLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 350, 50));

        userLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userLabel.setText("Usuario");
        userLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 350, 30));

        userTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userTextField.setBorder(null);
        userTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTextFieldKeyTyped(evt);
            }
        });
        mainPanel.add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 350, 20));

        userLine.setBackground(new java.awt.Color(102, 102, 102));
        userLine.setToolTipText("");

        javax.swing.GroupLayout userLineLayout = new javax.swing.GroupLayout(userLine);
        userLine.setLayout(userLineLayout);
        userLineLayout.setHorizontalGroup(
            userLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        userLineLayout.setVerticalGroup(
            userLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        mainPanel.add(userLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 350, 2));

        passwordLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLabel.setText("Contraseña");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 350, 30));

        passwordTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordTextField.setBorder(null);
        passwordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTextFieldKeyTyped(evt);
            }
        });
        mainPanel.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 350, 20));

        passwordLine.setBackground(new java.awt.Color(102, 102, 102));
        passwordLine.setToolTipText("");

        javax.swing.GroupLayout passwordLineLayout = new javax.swing.GroupLayout(passwordLine);
        passwordLine.setLayout(passwordLineLayout);
        passwordLineLayout.setHorizontalGroup(
            passwordLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        passwordLineLayout.setVerticalGroup(
            passwordLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        mainPanel.add(passwordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 350, 2));

        btnLogin.setBackground(new java.awt.Color(51, 23, 156));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoginLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLoginLabel.setText("Entrar");
        btnLoginLabel.setToolTipText("");
        btnLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginLabelMouseExited(evt);
            }
        });
        btnLogin.add(btnLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        mainPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 130, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decorativePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decorativePanelMousePressed
        
    }//GEN-LAST:event_decorativePanelMousePressed

    private void decorativePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decorativePanelMouseDragged
        
    }//GEN-LAST:event_decorativePanelMouseDragged

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
      
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
       
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        
    }//GEN-LAST:event_btnCloseMouseClicked

    private void userTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextFieldKeyTyped

    }//GEN-LAST:event_userTextFieldKeyTyped

    private void passwordTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextFieldKeyTyped
        
    }//GEN-LAST:event_passwordTextFieldKeyTyped

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
       
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginLabelMouseEntered
        
    }//GEN-LAST:event_btnLoginLabelMouseEntered

    private void btnLoginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginLabelMouseExited
        
    }//GEN-LAST:event_btnLoginLabelMouseExited

    private void btnLoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginLabelMouseClicked
       
    }//GEN-LAST:event_btnLoginLabelMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
       
    }//GEN-LAST:event_btnLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel alertBody;
    public javax.swing.JPanel alertPanel;
    public javax.swing.JLabel alertTitle;
    public javax.swing.JLabel btnClose;
    public javax.swing.JPanel btnLogin;
    public javax.swing.JLabel btnLoginLabel;
    public javax.swing.JPanel decorativePanel;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgTec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel mainPanel;
    public javax.swing.JLabel passwordLabel;
    public javax.swing.JPanel passwordLine;
    public javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel touchtrackLabel;
    public javax.swing.JLabel userLabel;
    public javax.swing.JPanel userLine;
    public javax.swing.JTextField userTextField;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
