package tec.views;

import tec.styles.JComboBoxCustom;

public class NewFingerprintRec extends javax.swing.JPanel {

    public NewFingerprintRec() { 
        initComponents();
    }
 
//    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fingerPrintBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboReaders = new JComboBoxCustom();
        fingerprintPanel1 = new javax.swing.JPanel();
        fingerprintImg1 = new javax.swing.JLabel();
        fingerprintPanel2 = new javax.swing.JPanel();
        fingerprintImg2 = new javax.swing.JLabel();
        fingerprintPanel3 = new javax.swing.JPanel();
        fingerprintImg3 = new javax.swing.JLabel();
        fingerprintPanel4 = new javax.swing.JPanel();
        fingerprintImg4 = new javax.swing.JLabel();
        btnFingerCapture = new javax.swing.JPanel();
        btnFingerCaptureLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        fingerPrintBody.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Seleccione el sensor");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboReaders.setEditable(true);
        comboReaders.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboReaders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargando..." }));

        fingerprintPanel1.setBackground(new java.awt.Color(255, 255, 255));
        fingerprintPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));
        fingerprintPanel1.setPreferredSize(new java.awt.Dimension(143, 183));

        fingerprintImg1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fingerprintPanel1Layout = new javax.swing.GroupLayout(fingerprintPanel1);
        fingerprintPanel1.setLayout(fingerprintPanel1Layout);
        fingerprintPanel1Layout.setHorizontalGroup(
            fingerprintPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fingerprintPanel1Layout.setVerticalGroup(
            fingerprintPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        fingerprintPanel2.setBackground(new java.awt.Color(255, 255, 255));
        fingerprintPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));
        fingerprintPanel2.setPreferredSize(new java.awt.Dimension(143, 183));

        fingerprintImg2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fingerprintPanel2Layout = new javax.swing.GroupLayout(fingerprintPanel2);
        fingerprintPanel2.setLayout(fingerprintPanel2Layout);
        fingerprintPanel2Layout.setHorizontalGroup(
            fingerprintPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        fingerprintPanel2Layout.setVerticalGroup(
            fingerprintPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        fingerprintPanel3.setBackground(new java.awt.Color(255, 255, 255));
        fingerprintPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));
        fingerprintPanel3.setPreferredSize(new java.awt.Dimension(143, 183));

        fingerprintImg3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fingerprintPanel3Layout = new javax.swing.GroupLayout(fingerprintPanel3);
        fingerprintPanel3.setLayout(fingerprintPanel3Layout);
        fingerprintPanel3Layout.setHorizontalGroup(
            fingerprintPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        fingerprintPanel3Layout.setVerticalGroup(
            fingerprintPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        fingerprintPanel4.setBackground(new java.awt.Color(255, 255, 255));
        fingerprintPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));
        fingerprintPanel4.setPreferredSize(new java.awt.Dimension(143, 183));

        fingerprintImg4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fingerprintPanel4Layout = new javax.swing.GroupLayout(fingerprintPanel4);
        fingerprintPanel4.setLayout(fingerprintPanel4Layout);
        fingerprintPanel4Layout.setHorizontalGroup(
            fingerprintPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fingerprintPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        fingerprintPanel4Layout.setVerticalGroup(
            fingerprintPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFingerCapture.setBackground(new java.awt.Color(51, 23, 156));
        btnFingerCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseExited(evt);
            }
        });

        btnFingerCaptureLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFingerCaptureLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnFingerCaptureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFingerCaptureLabel.setText("Capturar");
        btnFingerCaptureLabel.setToolTipText("");
        btnFingerCaptureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFingerCaptureLayout = new javax.swing.GroupLayout(btnFingerCapture);
        btnFingerCapture.setLayout(btnFingerCaptureLayout);
        btnFingerCaptureLayout.setHorizontalGroup(
            btnFingerCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFingerCaptureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        btnFingerCaptureLayout.setVerticalGroup(
            btnFingerCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFingerCaptureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        statusLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 14)); // NOI18N
        statusLabel.setText("En espera...");
        statusLabel.setToolTipText("");
        statusLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout fingerPrintBodyLayout = new javax.swing.GroupLayout(fingerPrintBody);
        fingerPrintBody.setLayout(fingerPrintBodyLayout);
        fingerPrintBodyLayout.setHorizontalGroup(
            fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fingerPrintBodyLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboReaders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                        .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFingerCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fingerprintPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(fingerprintPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(fingerprintPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(fingerprintPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGap(10, 10, 10))
        );
        fingerPrintBodyLayout.setVerticalGroup(
            fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(comboReaders, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFingerCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                        .addComponent(fingerprintPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fingerprintPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fingerprintPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fingerprintPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fingerPrintBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fingerPrintBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFingerCaptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseExited

    }//GEN-LAST:event_btnFingerCaptureMouseExited

    private void btnFingerCaptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseEntered

    }//GEN-LAST:event_btnFingerCaptureMouseEntered

    private void btnFingerCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseClicked
        //
    }//GEN-LAST:event_btnFingerCaptureMouseClicked

    private void btnFingerCaptureLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseExited

    }//GEN-LAST:event_btnFingerCaptureLabelMouseExited

    private void btnFingerCaptureLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseEntered

    }//GEN-LAST:event_btnFingerCaptureLabelMouseEntered

    private void btnFingerCaptureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseClicked

    }//GEN-LAST:event_btnFingerCaptureLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnFingerCapture;
    public javax.swing.JLabel btnFingerCaptureLabel;
    public javax.swing.JComboBox<String> comboReaders;
    private javax.swing.JPanel fingerPrintBody;
    public javax.swing.JLabel fingerprintImg1;
    public javax.swing.JLabel fingerprintImg2;
    public javax.swing.JLabel fingerprintImg3;
    public javax.swing.JLabel fingerprintImg4;
    public javax.swing.JPanel fingerprintPanel1;
    public javax.swing.JPanel fingerprintPanel2;
    public javax.swing.JPanel fingerprintPanel3;
    public javax.swing.JPanel fingerprintPanel4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
