package tec.views;

public class Panel extends javax.swing.JFrame {  
    public Panel() {             
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPanel = new javax.swing.JPanel();
        iconImg = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnFullSize = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logoTec = new javax.swing.JLabel();
        btn1 = new javax.swing.JPanel();
        btn1Bar = new javax.swing.JPanel();
        btn1Label = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        btn3Bar = new javax.swing.JPanel();
        btn3Label = new javax.swing.JLabel();
        btn4 = new javax.swing.JPanel();
        btn4Bar = new javax.swing.JPanel();
        btn4Label = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        btn5Bar = new javax.swing.JPanel();
        btn5Label = new javax.swing.JLabel();
        btn5Label1 = new javax.swing.JLabel();
        btn5Label2 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        barPanel.setBackground(new java.awt.Color(51, 23, 156));
        barPanel.setPreferredSize(new java.awt.Dimension(183, 34));
        barPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barPanelMouseDragged(evt);
            }
        });
        barPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barPanelMousePressed(evt);
            }
        });

        iconImg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iconImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/touchtrack20px.png"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("TouchTrack - V.2.0.0");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/iconCloseWhite.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        btnFullSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/max.png"))); // NOI18N
        btnFullSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFullSizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFullSizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFullSizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout barPanelLayout = new javax.swing.GroupLayout(barPanel);
        barPanel.setLayout(barPanelLayout);
        barPanelLayout.setHorizontalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconImg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(titleLabel)
                .addGap(117, 117, 117)
                .addComponent(btnFullSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(3, 3, 3))
        );
        barPanelLayout.setVerticalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(barPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addComponent(btnFullSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        leftPanel.setBackground(new java.awt.Color(51, 23, 156));
        leftPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        leftPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                leftPanelMouseDragged(evt);
            }
        });
        leftPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leftPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                leftPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        bottomPanel.setBackground(new java.awt.Color(51, 23, 156));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        rightPanel.setBackground(new java.awt.Color(51, 23, 156));
        rightPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        rightPanel.setPreferredSize(new java.awt.Dimension(2, 0));
        rightPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rightPanelMouseDragged(evt);
            }
        });
        rightPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuPanel.setBackground(new java.awt.Color(51, 23, 156));
        menuPanel.setPreferredSize(new java.awt.Dimension(260, 0));

        logoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/tec-efecto.png"))); // NOI18N

        btn1.setBackground(new java.awt.Color(51, 23, 156));
        btn1.setPreferredSize(new java.awt.Dimension(206, 50));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });

        btn1Bar.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout btn1BarLayout = new javax.swing.GroupLayout(btn1Bar);
        btn1Bar.setLayout(btn1BarLayout);
        btn1BarLayout.setHorizontalGroup(
            btn1BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        btn1BarLayout.setVerticalGroup(
            btn1BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn1Label.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn1Label.setForeground(new java.awt.Color(255, 255, 255));
        btn1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/huella.png"))); // NOI18N
        btn1Label.setText("Registrar huella");
        btn1Label.setToolTipText("");
        btn1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn1Layout = new javax.swing.GroupLayout(btn1);
        btn1.setLayout(btn1Layout);
        btn1Layout.setHorizontalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn1Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn1Layout.setVerticalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn1Layout.createSequentialGroup()
                .addGroup(btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1Bar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn3.setBackground(new java.awt.Color(51, 23, 156));
        btn3.setPreferredSize(new java.awt.Dimension(206, 50));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });

        btn3Bar.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout btn3BarLayout = new javax.swing.GroupLayout(btn3Bar);
        btn3Bar.setLayout(btn3BarLayout);
        btn3BarLayout.setHorizontalGroup(
            btn3BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        btn3BarLayout.setVerticalGroup(
            btn3BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btn3Label.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn3Label.setForeground(new java.awt.Color(255, 255, 255));
        btn3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/escaneo.png"))); // NOI18N
        btn3Label.setText("<html><p>Registrar asistencia por evento</p></html>");
        btn3Label.setToolTipText("");
        btn3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn3Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addGroup(btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btn3Layout.createSequentialGroup()
                        .addComponent(btn3Label)
                        .addGap(7, 7, 7))
                    .addComponent(btn3Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn4.setBackground(new java.awt.Color(51, 23, 156));
        btn4.setPreferredSize(new java.awt.Dimension(206, 50));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
        });

        btn4Bar.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout btn4BarLayout = new javax.swing.GroupLayout(btn4Bar);
        btn4Bar.setLayout(btn4BarLayout);
        btn4BarLayout.setHorizontalGroup(
            btn4BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        btn4BarLayout.setVerticalGroup(
            btn4BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btn4Label.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn4Label.setForeground(new java.awt.Color(255, 255, 255));
        btn4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/home.png"))); // NOI18N
        btn4Label.setText("Inicio");
        btn4Label.setToolTipText("");
        btn4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn4Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn4Layout.createSequentialGroup()
                .addGroup(btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4Bar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn4Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn5.setBackground(new java.awt.Color(51, 23, 156));
        btn5.setPreferredSize(new java.awt.Dimension(206, 50));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
        });

        btn5Bar.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout btn5BarLayout = new javax.swing.GroupLayout(btn5Bar);
        btn5Bar.setLayout(btn5BarLayout);
        btn5BarLayout.setHorizontalGroup(
            btn5BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        btn5BarLayout.setVerticalGroup(
            btn5BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btn5Label.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn5Label.setForeground(new java.awt.Color(255, 255, 255));
        btn5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tec/images/escaneo2.png"))); // NOI18N
        btn5Label.setText("<html><p>Registrar asistencia</p></html>");
        btn5Label.setToolTipText("");
        btn5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn5Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn5Layout.createSequentialGroup()
                .addGroup(btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5Bar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn5Label1.setFont(new java.awt.Font("MadaniArabic-Regular", 0, 10)); // NOI18N
        btn5Label1.setForeground(new java.awt.Color(255, 255, 255));
        btn5Label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn5Label1.setText("<html>\n<p>Jesus Navarro Salcido, Vanessa Guadalupe Ramirez Sanchez, Jorge Garcia Rodriguez, Alejandro Torres Padilla, Miguel Jimenez Vivanco, Martha Nayeli Beltran Garnica, Brayan Moises Felix Aguirre, Brian Valdivia Navarro</p>\n</html>");
        btn5Label1.setToolTipText("");
        btn5Label1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn5Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5Label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5Label1MouseExited(evt);
            }
        });

        btn5Label2.setFont(new java.awt.Font("MadaniArabic-SemiBold", 0, 12)); // NOI18N
        btn5Label2.setForeground(new java.awt.Color(255, 255, 255));
        btn5Label2.setText("<html><p>Equipo:</p></html>");
        btn5Label2.setToolTipText("");
        btn5Label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5Label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5Label2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(logoTec)
                .addGap(0, 67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5Label2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn5Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(logoTec)
                .addGap(48, 48, 48)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn5Label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn5Label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btn4.setVisible(false);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(barPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelMouseReleased

    }//GEN-LAST:event_leftPanelMouseReleased

    private void leftPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelMousePressed

    }//GEN-LAST:event_leftPanelMousePressed

    private void leftPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelMouseDragged

    }//GEN-LAST:event_leftPanelMouseDragged

    private void rightPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightPanelMousePressed
        
    }//GEN-LAST:event_rightPanelMousePressed

    private void rightPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightPanelMouseReleased
    }//GEN-LAST:event_rightPanelMouseReleased

    private void rightPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightPanelMouseDragged
         
    }//GEN-LAST:event_rightPanelMouseDragged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
    }//GEN-LAST:event_formComponentResized

    private void barPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barPanelMousePressed
       
    }//GEN-LAST:event_barPanelMousePressed

    private void barPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barPanelMouseDragged

    }//GEN-LAST:event_barPanelMouseDragged

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
  
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
    }//GEN-LAST:event_btn1MouseExited

    private void btn1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1LabelMouseEntered
    }//GEN-LAST:event_btn1LabelMouseEntered

    private void btn1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1LabelMouseExited
    }//GEN-LAST:event_btn1LabelMouseExited

    private void btn3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3LabelMouseEntered
    }//GEN-LAST:event_btn3LabelMouseEntered

    private void btn3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3LabelMouseExited
    }//GEN-LAST:event_btn3LabelMouseExited

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
    }//GEN-LAST:event_btn3MouseExited

    private void btn4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4LabelMouseEntered
    }//GEN-LAST:event_btn4LabelMouseEntered

    private void btn4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4LabelMouseExited
    }//GEN-LAST:event_btn4LabelMouseExited

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
    }//GEN-LAST:event_btn4MouseEntered

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
    }//GEN-LAST:event_btn4MouseExited

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
    }//GEN-LAST:event_btn1MouseClicked

    private void btn4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4LabelMouseClicked
    }//GEN-LAST:event_btn4LabelMouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
    }//GEN-LAST:event_btn4MouseClicked

    private void btn1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1LabelMouseClicked
    }//GEN-LAST:event_btn1LabelMouseClicked

    private void btnFullSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFullSizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFullSizeMouseClicked

    private void btnFullSizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFullSizeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFullSizeMouseEntered

    private void btnFullSizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFullSizeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFullSizeMouseExited

    private void btn5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5LabelMouseEntered

    private void btn5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5LabelMouseExited

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseEntered

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseExited

    private void btn5Label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5Label1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5Label1MouseEntered

    private void btn5Label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5Label1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5Label1MouseExited

    private void btn5Label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5Label2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5Label2MouseEntered

    private void btn5Label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5Label2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5Label2MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel barPanel;
    private javax.swing.JPanel bottomPanel;
    public javax.swing.JPanel btn1;
    private javax.swing.JPanel btn1Bar;
    public javax.swing.JLabel btn1Label;
    public javax.swing.JPanel btn3;
    private javax.swing.JPanel btn3Bar;
    public javax.swing.JLabel btn3Label;
    public javax.swing.JPanel btn4;
    private javax.swing.JPanel btn4Bar;
    public javax.swing.JLabel btn4Label;
    public javax.swing.JPanel btn5;
    private javax.swing.JPanel btn5Bar;
    public javax.swing.JLabel btn5Label;
    public javax.swing.JLabel btn5Label1;
    public javax.swing.JLabel btn5Label2;
    public javax.swing.JLabel btnClose;
    public javax.swing.JLabel btnFullSize;
    public javax.swing.JPanel contentPanel;
    private javax.swing.JLabel iconImg;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoTec;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
