package tec.views;

import tec.styles.JComboBoxCustom;

public class VerifyFingerprintRec extends javax.swing.JPanel {

    public VerifyFingerprintRec() { 
        initComponents();
    }
 
//    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fingerPrintBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboReaders = new JComboBoxCustom();
        fingerprintPanel = new javax.swing.JPanel();
        fingerprintImg = new javax.swing.JLabel();
        btnFingerCapture = new javax.swing.JPanel();
        btnFingerCaptureLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fingerprintLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        verificationLabel = new javax.swing.JLabel();

        fingerPrintBody.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Seleccione el sensor");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboReaders.setEditable(true);
        comboReaders.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboReaders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargando..." }));

        fingerprintPanel.setBackground(new java.awt.Color(255, 255, 255));
        fingerprintPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 23, 156), 2, true));

        fingerprintImg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fingerprintPanelLayout = new javax.swing.GroupLayout(fingerprintPanel);
        fingerprintPanel.setLayout(fingerprintPanelLayout);
        fingerprintPanelLayout.setHorizontalGroup(
            fingerprintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fingerprintPanelLayout.setVerticalGroup(
            fingerprintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerprintPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fingerprintImg, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFingerCapture.setBackground(new java.awt.Color(51, 23, 156));
        btnFingerCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFingerCaptureMouseExited(evt);
            }
        });

        btnFingerCaptureLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFingerCaptureLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnFingerCaptureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFingerCaptureLabel.setText("Capturar");
        btnFingerCaptureLabel.setToolTipText("");
        btnFingerCaptureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFingerCaptureLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFingerCaptureLayout = new javax.swing.GroupLayout(btnFingerCapture);
        btnFingerCapture.setLayout(btnFingerCaptureLayout);
        btnFingerCaptureLayout.setHorizontalGroup(
            btnFingerCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFingerCaptureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFingerCaptureLayout.setVerticalGroup(
            btnFingerCaptureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFingerCaptureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        statusLabel.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 14)); // NOI18N
        statusLabel.setText("En espera...");
        statusLabel.setToolTipText("");
        statusLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ID:");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        fingerprintLabel.setFont(new java.awt.Font("MadaniArabic-Regular", 0, 14)); // NOI18N
        fingerprintLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fingerprintLabel.setText("Sin resultados.");
        fingerprintLabel.setToolTipText("");
        fingerprintLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Fecha");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dateLabel.setFont(new java.awt.Font("MadaniArabic-Regular", 0, 14)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateLabel.setText("Sin resultados.");
        dateLabel.setToolTipText("");
        dateLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setFont(new java.awt.Font("MadaniArabic-Medium", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Verificacion");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        verificationLabel.setFont(new java.awt.Font("MadaniArabic-Regular", 0, 14)); // NOI18N
        verificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verificationLabel.setText("Sin resultados.");
        verificationLabel.setToolTipText("");
        verificationLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout fingerPrintBodyLayout = new javax.swing.GroupLayout(fingerPrintBody);
        fingerPrintBody.setLayout(fingerPrintBodyLayout);
        fingerPrintBodyLayout.setHorizontalGroup(
            fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboReaders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                        .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnFingerCapture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fingerprintPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fingerprintLabel))
                                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateLabel))
                                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(verificationLabel)))))
                        .addGap(0, 384, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fingerPrintBodyLayout.setVerticalGroup(
            fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(comboReaders, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFingerCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fingerprintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fingerPrintBodyLayout.createSequentialGroup()
                        .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fingerprintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(fingerPrintBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fingerPrintBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fingerPrintBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFingerCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseClicked
//      
    }//GEN-LAST:event_btnFingerCaptureMouseClicked

    private void btnFingerCaptureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseEntered
    }//GEN-LAST:event_btnFingerCaptureMouseEntered

    private void btnFingerCaptureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureMouseExited

    }//GEN-LAST:event_btnFingerCaptureMouseExited

    private void btnFingerCaptureLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseExited

    }//GEN-LAST:event_btnFingerCaptureLabelMouseExited

    private void btnFingerCaptureLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseEntered

    }//GEN-LAST:event_btnFingerCaptureLabelMouseEntered

    private void btnFingerCaptureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFingerCaptureLabelMouseClicked

    }//GEN-LAST:event_btnFingerCaptureLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnFingerCapture;
    public javax.swing.JLabel btnFingerCaptureLabel;
    public javax.swing.JComboBox<String> comboReaders;
    public javax.swing.JLabel dateLabel;
    private javax.swing.JPanel fingerPrintBody;
    public javax.swing.JLabel fingerprintImg;
    public javax.swing.JLabel fingerprintLabel;
    public javax.swing.JPanel fingerprintPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel statusLabel;
    public javax.swing.JLabel verificationLabel;
    // End of variables declaration//GEN-END:variables
}
